theme:        jekyll-theme-minimal
title:        Tobias Morrison
tagline:      MacAdmin
description:  An Apple Systems Administrator focusing on great employee experiences via scripting and profiles.
